<?php
// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

namespace App\Services;

use App\Core\TenantContext;
use App\I18n\LocaleContext;
use App\Support\Authorization\SafeguardingStaff;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * MatchApprovalWorkflowService — Broker approval workflow for match suggestions.
 *
 * All matches generated by SmartMatchingEngine flow through this service before
 * being surfaced to users. Admins/brokers can approve or reject matches.
 *
 * Tables: match_approvals
 */
class MatchApprovalWorkflowService
{
    public function __construct()
    {
    }

    /**
     * Submit a match for admin/broker approval.
     *
     * Inserts a new pending match_approvals row. Returns the ID on success,
     * null if a duplicate pending row already exists or on error.
     */
    public static function submitForApproval(int $userId, int $listingId, array $matchData): ?int
    {
        $tenantId = TenantContext::getId();

        try {
            // Resolve listing owner
            $listing = DB::table('listings')
                ->where('id', $listingId)
                ->where('tenant_id', $tenantId)
                ->select('user_id')
                ->first();

            if (!$listing) {
                Log::warning('[MatchApprovalWorkflow] Listing not found', [
                    'listing_id' => $listingId,
                    'tenant_id' => $tenantId,
                ]);
                return null;
            }

            $listingOwnerId = (int) $listing->user_id;

            // Don't match user with themselves
            if ($userId === $listingOwnerId) {
                return null;
            }

            // This queue exists for exactly the pairs MatchApprovalGate holds
            // back (a safeguarding "coordinator approval" / "restrict matching"
            // choice, or administrative monitoring). Until 29 Sep 2026 this
            // method refused those pairs, so the queue could never fill. A pair
            // the contact policy forbids outright is still never queued.
            if (! self::contactPolicyAllowsBoth($userId, $listingOwnerId, $tenantId, 'match_submission')) {
                return null;
            }

            $matchType = $matchData['match_type'] ?? $matchData['type'] ?? 'one_way';

            $id = DB::table('match_approvals')->insertGetId([
                'tenant_id' => $tenantId,
                'user_id' => $userId,
                'listing_id' => $listingId,
                'listing_owner_id' => $listingOwnerId,
                'match_score' => (float) ($matchData['match_score'] ?? $matchData['score'] ?? 0),
                'match_type' => $matchType,
                'match_reasons' => json_encode($matchData['match_reasons'] ?? $matchData['reasons'] ?? []),
                'distance_km' => $matchData['distance_km'] ?? $matchData['distance'] ?? null,
                'status' => 'pending',
                'submitted_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Look up names for notifications (used by both broker and mutual match notifications)
            $userName = null;
            $listingTitle = null;
            try {
                $userName = DB::table('users')
                    ->where('id', $userId)
                    ->where('tenant_id', $tenantId)
                    ->value(DB::raw("CONCAT(COALESCE(first_name, ''), ' ', COALESCE(last_name, ''))"));
                $listingTitle = DB::table('listings')
                    ->where('id', $listingId)
                    ->where('tenant_id', $tenantId)
                    ->value('title');
            } catch (\Throwable $e) {
                Log::warning('[MatchApprovalWorkflow] Failed to look up names for notifications', [
                    'error' => $e->getMessage(),
                ]);
            }

            // Notify brokers/admins that a match needs approval.
            // The fallback_member_name is rendered per-broker under their
            // preferred_language so it doesn't leak the caller's locale into
            // the recipient's bell. The downstream dispatcher already wraps
            // under LocaleContext for the notification text itself.
            try {
                $brokers = SafeguardingStaff::scope(
                    DB::table('users')->where('tenant_id', $tenantId)->where('status', 'active')
                )
                    ->where('id', '!=', $userId)
                    ->where('id', '!=', $listingOwnerId)
                    ->select(['id', 'preferred_language'])
                    ->get();

                foreach ($brokers as $broker) {
                    $trimmedUserName = trim((string) ($userName ?? ''));
                    $resolvedName = $trimmedUserName !== ''
                        ? $trimmedUserName
                        : LocaleContext::withLocale($broker, fn () => __('emails.common.fallback_member_name'));

                    NotificationDispatcher::dispatchMatchApprovalRequest(
                        (int) $broker->id,
                        $resolvedName,
                        $listingTitle ?? 'a listing',
                        (int) $id
                    );
                }
            } catch (\Throwable $e) {
                Log::warning('[MatchApprovalWorkflow] Failed to notify brokers', [
                    'request_id' => $id,
                    'error' => $e->getMessage(),
                ]);
            }

            // Neither member is told anything at submission: the pair has not
            // been approved yet. Both are told on approval (approveMatch).

            return (int) $id;
        } catch (\Throwable $e) {
            // Likely a duplicate key violation (unique_pending_match constraint)
            if (str_contains($e->getMessage(), 'Duplicate entry')) {
                Log::info('[MatchApprovalWorkflow] Duplicate pending match ignored', [
                    'user_id' => $userId,
                    'listing_id' => $listingId,
                ]);
                return null;
            }

            Log::error('[MatchApprovalWorkflow] submitForApproval failed', [
                'user_id' => $userId,
                'listing_id' => $listingId,
                'error' => $e->getMessage(),
            ]);
            return null;
        }
    }

    /**
     * Approve a pending match approval request.
     *
     * Returns true if the row was updated (was pending), false if not found
     * or already reviewed.
     */
    public static function approveMatch(int $requestId, int $approvedBy, string $notes = ''): bool
    {
        $tenantId = TenantContext::getId();

        try {
            // Fetch the approval row before updating so we have data for notifications
            $approval = DB::table('match_approvals')
                ->where('id', $requestId)
                ->where('tenant_id', $tenantId)
                ->where('status', 'pending')
                ->first();

            if (!$approval) {
                return false;
            }

            if (! self::contactPolicyAllowsBoth(
                (int) $approval->user_id,
                (int) $approval->listing_owner_id,
                $tenantId,
                'match_approval',
            )) {
                return false;
            }

            $affected = DB::table('match_approvals')
                ->where('id', $requestId)
                ->where('tenant_id', $tenantId)
                ->where('status', 'pending')
                ->update([
                    'status' => 'approved',
                    'reviewed_by' => $approvedBy,
                    'reviewed_at' => now(),
                    'review_notes' => $notes ?: null,
                    'updated_at' => now(),
                ]);

            if ($affected > 0) {
                Log::info('[MatchApprovalWorkflow] Match approved', [
                    'request_id' => $requestId,
                    'approved_by' => $approvedBy,
                ]);

                // Notify the matched user that their match was approved
                try {
                    $listingTitle = DB::table('listings')
                        ->where('id', (int) $approval->listing_id)
                        ->where('tenant_id', $tenantId)
                        ->value('title') ?? 'a listing';

                    NotificationDispatcher::dispatchMatchApproved(
                        (int) $approval->user_id,
                        $listingTitle,
                        (int) $approval->listing_id,
                        (int) ($approval->match_score ?? 0)
                    );
                    NotificationDispatcher::dispatchMatchApprovedForOwner(
                        (int) $approval->listing_owner_id,
                        (int) $approval->user_id,
                        $listingTitle,
                        (int) $approval->listing_id
                    );
                } catch (\Throwable $e) {
                    Log::warning('[MatchApprovalWorkflow] Failed to dispatch match approved notification', [
                        'request_id' => $requestId,
                        'error' => $e->getMessage(),
                    ]);
                }

                return true;
            }

            return false;
        } catch (\Throwable $e) {
            Log::error('[MatchApprovalWorkflow] approveMatch failed', [
                'request_id' => $requestId,
                'error' => $e->getMessage(),
            ]);
            return false;
        }
    }

    /**
     * Reject a pending match approval request.
     *
     * Returns true if the row was updated (was pending), false if not found
     * or already reviewed.
     */
    public static function rejectMatch(int $requestId, int $rejectedBy, string $reason = ''): bool
    {
        $tenantId = TenantContext::getId();

        try {
            // Fetch the approval row before updating so we have data for notifications
            $approval = DB::table('match_approvals')
                ->where('id', $requestId)
                ->where('tenant_id', $tenantId)
                ->where('status', 'pending')
                ->first();

            if (!$approval) {
                return false;
            }

            $affected = DB::table('match_approvals')
                ->where('id', $requestId)
                ->where('tenant_id', $tenantId)
                ->where('status', 'pending')
                ->update([
                    'status' => 'rejected',
                    'reviewed_by' => $rejectedBy,
                    'reviewed_at' => now(),
                    'review_notes' => $reason ?: null,
                    'updated_at' => now(),
                ]);

            if ($affected > 0) {
                Log::info('[MatchApprovalWorkflow] Match rejected', [
                    'request_id' => $requestId,
                    'rejected_by' => $rejectedBy,
                    'reason' => $reason,
                ]);

                // Deliberately silent to both members: neither was ever shown
                // this proposal (MatchApprovalGate withheld it), and the
                // reviewer's reason can carry safeguarding detail. The
                // rejected row keeps the pair from being proposed again, and
                // the controller writes the audit entry.

                return true;
            }

            return false;
        } catch (\Throwable $e) {
            Log::error('[MatchApprovalWorkflow] rejectMatch failed', [
                'request_id' => $requestId,
                'error' => $e->getMessage(),
            ]);
            return false;
        }
    }

    /**
     * Bulk approve multiple pending match approval requests.
     *
     * @param int[] $requestIds
     * @return int Number of rows actually approved
     */
    public static function bulkApprove(array $requestIds, int $approvedBy, string $notes = ''): int
    {
        if (empty($requestIds)) {
            return 0;
        }

        $tenantId = TenantContext::getId();

        try {
            $placeholders = implode(',', array_fill(0, count($requestIds), '?'));

            // Fetch pending rows before updating so we can notify users
            $pendingRows = DB::select(
                "SELECT ma.id, ma.user_id, ma.listing_owner_id, ma.listing_id, ma.match_score, l.title as listing_title
                 FROM match_approvals ma
                 LEFT JOIN listings l ON ma.listing_id = l.id
                 WHERE ma.id IN ({$placeholders})
                   AND ma.tenant_id = ?
                   AND ma.status = 'pending'",
                array_merge(
                    array_map('intval', $requestIds),
                    [$tenantId]
                )
            );

            foreach ($pendingRows as $row) {
                if (! self::contactPolicyAllowsBoth(
                    (int) $row->user_id,
                    (int) $row->listing_owner_id,
                    $tenantId,
                    'match_bulk_approval',
                )) {
                    return 0;
                }
            }

            $affected = DB::update(
                "UPDATE match_approvals
                 SET status = 'approved',
                     reviewed_by = ?,
                     reviewed_at = NOW(),
                     review_notes = ?,
                     updated_at = NOW()
                 WHERE id IN ({$placeholders})
                   AND tenant_id = ?
                   AND status = 'pending'",
                array_merge(
                    [$approvedBy, $notes ?: null],
                    array_map('intval', $requestIds),
                    [$tenantId]
                )
            );

            if ($affected > 0) {
                Log::info('[MatchApprovalWorkflow] Bulk approve', [
                    'count' => $affected,
                    'approved_by' => $approvedBy,
                ]);

                // Notify each affected user
                try {
                    foreach ($pendingRows as $row) {
                        NotificationDispatcher::dispatchMatchApproved(
                            (int) $row->user_id,
                            $row->listing_title ?? 'a listing',
                            (int) $row->listing_id,
                            (int) ($row->match_score ?? 0)
                        );
                        NotificationDispatcher::dispatchMatchApprovedForOwner(
                            (int) $row->listing_owner_id,
                            (int) $row->user_id,
                            $row->listing_title ?? 'a listing',
                            (int) $row->listing_id
                        );
                    }
                } catch (\Throwable $e) {
                    Log::warning('[MatchApprovalWorkflow] Failed to dispatch bulk approve notifications', [
                        'error' => $e->getMessage(),
                    ]);
                }
            }

            return $affected;
        } catch (\Throwable $e) {
            Log::error('[MatchApprovalWorkflow] bulkApprove failed', [
                'ids' => $requestIds,
                'error' => $e->getMessage(),
            ]);
            return 0;
        }
    }

    /**
     * Bulk reject multiple pending match approval requests.
     *
     * @param int[] $requestIds
     * @return int Number of rows actually rejected
     */
    public static function bulkReject(array $requestIds, int $rejectedBy, string $reason = ''): int
    {
        if (empty($requestIds)) {
            return 0;
        }

        $tenantId = TenantContext::getId();

        try {
            $placeholders = implode(',', array_fill(0, count($requestIds), '?'));

            $affected = DB::update(
                "UPDATE match_approvals
                 SET status = 'rejected',
                     reviewed_by = ?,
                     reviewed_at = NOW(),
                     review_notes = ?,
                     updated_at = NOW()
                 WHERE id IN ({$placeholders})
                   AND tenant_id = ?
                   AND status = 'pending'",
                array_merge(
                    [$rejectedBy, $reason ?: null],
                    array_map('intval', $requestIds),
                    [$tenantId]
                )
            );

            if ($affected > 0) {
                Log::info('[MatchApprovalWorkflow] Bulk reject', [
                    'count' => $affected,
                    'rejected_by' => $rejectedBy,
                ]);

                // Silent to members for the same reason as rejectMatch().
            }

            return $affected;
        } catch (\Throwable $e) {
            Log::error('[MatchApprovalWorkflow] bulkReject failed', [
                'ids' => $requestIds,
                'error' => $e->getMessage(),
            ]);
            return 0;
        }
    }

    /**
     * Get approval workflow statistics for the current tenant.
     *
     * @param int $days Lookback window in days (default 30)
     * @return array{total: int, pending: int, approved: int, rejected: int, approval_rate: float, avg_review_hours: float, top_reviewers: array}
     */
    public static function getStatistics(int $days = 30): array
    {
        $tenantId = TenantContext::getId();
        $since = now()->subDays($days)->toDateTimeString();

        try {
            // Aggregate counts
            $rows = DB::select(
                "SELECT status, COUNT(*) as cnt
                 FROM match_approvals
                 WHERE tenant_id = ? AND submitted_at >= ?
                 GROUP BY status",
                [$tenantId, $since]
            );

            $counts = ['pending' => 0, 'approved' => 0, 'rejected' => 0];
            foreach ($rows as $row) {
                $counts[$row->status] = (int) $row->cnt;
            }

            // Pending is a live review queue, not activity history — count it
            // WITHOUT the time window. A match submitted 40 days ago that
            // nobody reviewed must still light up the stat card, the tab
            // chip, and the broker sidebar badge; the windowed query silently
            // dropped exactly the items that most need attention.
            $counts['pending'] = (int) DB::selectOne(
                "SELECT COUNT(*) as cnt FROM match_approvals WHERE tenant_id = ? AND status = 'pending'",
                [$tenantId]
            )->cnt;

            $total = array_sum($counts);
            $reviewed = $counts['approved'] + $counts['rejected'];
            $approvalRate = $reviewed > 0
                ? round(($counts['approved'] / $reviewed) * 100, 1)
                : 0.0;

            // Average review time (hours between submitted_at and reviewed_at)
            $avgReview = DB::selectOne(
                "SELECT AVG(TIMESTAMPDIFF(HOUR, submitted_at, reviewed_at)) as avg_hours
                 FROM match_approvals
                 WHERE tenant_id = ? AND submitted_at >= ? AND reviewed_at IS NOT NULL",
                [$tenantId, $since]
            );
            $avgReviewHours = $avgReview && $avgReview->avg_hours !== null
                ? round((float) $avgReview->avg_hours, 1)
                : 0.0;

            // Top reviewers
            $reviewers = DB::select(
                "SELECT ma.reviewed_by,
                        CONCAT(COALESCE(u.first_name, ''), ' ', COALESCE(u.last_name, '')) as reviewer_name,
                        COUNT(*) as review_count,
                        SUM(CASE WHEN ma.status = 'approved' THEN 1 ELSE 0 END) as approved_count,
                        SUM(CASE WHEN ma.status = 'rejected' THEN 1 ELSE 0 END) as rejected_count
                 FROM match_approvals ma
                 JOIN users u ON ma.reviewed_by = u.id
                 WHERE ma.tenant_id = ? AND ma.submitted_at >= ? AND ma.reviewed_by IS NOT NULL
                 GROUP BY ma.reviewed_by, u.first_name, u.last_name
                 ORDER BY review_count DESC
                 LIMIT 10",
                [$tenantId, $since]
            );

            $topReviewers = array_map(fn($r) => [
                'user_id' => (int) $r->reviewed_by,
                'name' => trim($r->reviewer_name),
                'review_count' => (int) $r->review_count,
                'approved_count' => (int) $r->approved_count,
                'rejected_count' => (int) $r->rejected_count,
            ], $reviewers);

            return [
                'total' => $total,
                'pending' => $counts['pending'],
                'approved' => $counts['approved'],
                'rejected' => $counts['rejected'],
                // *_count aliases — the admin and broker MatchApprovals UIs
                // (MatchApprovalStats type) read these names; without them the
                // stat cards / pending badges rendered 0 forever.
                'pending_count' => $counts['pending'],
                'approved_count' => $counts['approved'],
                'rejected_count' => $counts['rejected'],
                'avg_approval_time' => $avgReviewHours,
                'approval_rate' => $approvalRate,
                'avg_review_hours' => $avgReviewHours,
                'days' => $days,
                'top_reviewers' => $topReviewers,
            ];
        } catch (\Throwable $e) {
            Log::error('[MatchApprovalWorkflow] getStatistics failed', [
                'error' => $e->getMessage(),
            ]);
            return [
                'total' => 0,
                'pending' => 0,
                'approved' => 0,
                'rejected' => 0,
                'pending_count' => 0,
                'approved_count' => 0,
                'rejected_count' => 0,
                'avg_approval_time' => 0.0,
                'approval_rate' => 0.0,
                'avg_review_hours' => 0.0,
                'days' => $days,
                'top_reviewers' => [],
            ];
        }
    }

    private static function contactPolicyAllowsBoth(
        int $firstUserId,
        int $secondUserId,
        int $tenantId,
        string $channel,
    ): bool {
        $policy = app(SafeguardingInteractionPolicy::class);
        foreach ([[$firstUserId, $secondUserId], [$secondUserId, $firstUserId]] as [$senderId, $recipientId]) {
            $decision = $policy->evaluateLocalContact($senderId, $recipientId, $tenantId, $channel);
            if (! $decision->isAllowed()) {
                Log::info('[MatchApprovalWorkflow] Blocked by safeguarding contact policy', [
                    'tenant_id' => $tenantId,
                    'sender_id' => $senderId,
                    'recipient_id' => $recipientId,
                    'reason_code' => $decision->code,
                    'channel' => $channel,
                ]);

                return false;
            }
        }

        return true;
    }
}
