#!/usr/bin/env bash
#
# Installs the repo's git hooks into .git/hooks.
#
# Run once per clone/machine:
#   bash scripts/git-hooks/install-hooks.sh
#
# Installs a thin SHIM that execs the tracked hook, rather than copying it.
#
# 🔴 Why a shim, changed 2026-08-22. This script used to `cp` the hook into
# .git/hooks, which makes the installed copy a point-in-time snapshot with
# nothing to detect staleness. That failed in exactly the way you would expect,
# twice over:
#
#   - a373010b9 (2026-08-10) "restore the lost credential-scan hook" added GATE A
#     to scripts/git-hooks/pre-commit. Nobody re-ran this installer, so the
#     installed copy stayed on the 2026-08-04 version. For twelve days this
#     PUBLIC repository had no local credential scan at all — the commit that
#     fixed the lost hook did not fix the installed hook.
#   - The same snapshot was also stuck on the host-PHPUnit version of GATE B,
#     which on a Windows dev box can only ever skip.
#
# A shim cannot drift: the tracked file IS the hook. Editing
# scripts/git-hooks/pre-commit takes effect on the next commit with no
# reinstall, and `git checkout` of an older commit correctly gets that commit's
# hook.
#
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
SRC="$ROOT/scripts/git-hooks"
DEST="$ROOT/.git/hooks"

mkdir -p "$DEST"

for hook in pre-commit; do
  [ -f "$SRC/$hook" ] || continue

  # `sh "$HOOK"` rather than `exec "$HOOK"`: git on Windows does not reliably
  # preserve the executable bit, so invoking the interpreter explicitly is the
  # portable form. Losing +x would otherwise silently disable the hook — the
  # same class of quiet failure this shim exists to prevent.
  cat > "$DEST/$hook" <<SHIM
#!/bin/sh
# GENERATED by scripts/git-hooks/install-hooks.sh — do not edit.
# The real hook is the tracked file below, so this shim can never go stale.
ROOT=\$(git rev-parse --show-toplevel) || exit 0
HOOK="\$ROOT/scripts/git-hooks/$hook"
if [ ! -f "\$HOOK" ]; then
  echo "$hook: \$HOOK is missing — hook cannot run." >&2
  echo "Re-run: bash scripts/git-hooks/install-hooks.sh" >&2
  exit 1
fi
sh "\$HOOK" "\$@"
SHIM

  chmod +x "$DEST/$hook"
  echo "installed: .git/hooks/$hook -> scripts/git-hooks/$hook (shim)"
done

echo ""
echo "Done. Both pre-commit gates are now live:"
echo "  GATE A  credential scan          — every commit (needs git + grep)"
echo "  GATE B  staged PHP test verify   — when tests/*Test.php is staged"
echo "          (runs phpunit inside the nexus-php-app container; BLOCKS if"
echo "           the container is unavailable, rather than skipping quietly)"
