#!/usr/bin/env bash
#
# Installs the repo's git hooks into .git/hooks.
#
# Run once per clone/machine:
#   bash scripts/git-hooks/install-hooks.sh
#
# Installs a thin SHIM that execs the tracked hook, rather than copying it.
#
# 🔴 Why a shim, changed 2026-08-22. This script used to `cp` the hook into
# .git/hooks, which makes the installed copy a point-in-time snapshot with
# nothing to detect staleness. That failed in exactly the way you would expect,
# twice over:
#
#   - a373010b9 (2026-08-10) "restore the lost credential-scan hook" added GATE A
#     to scripts/git-hooks/pre-commit. Nobody re-ran this installer, so the
#     installed copy stayed on the 2026-08-04 version. For twelve days this
#     PUBLIC repository had no local credential scan at all — the commit that
#     fixed the lost hook did not fix the installed hook.
#   - The same snapshot was also stuck on the host-PHPUnit version of GATE B,
#     which on a Windows dev box can only ever skip.
#
# A shim cannot drift: the tracked file IS the hook. Editing
# scripts/git-hooks/pre-commit takes effect on the next commit with no
# reinstall, and `git checkout` of an older commit correctly gets that commit's
# hook.
#
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
SRC="$ROOT/scripts/git-hooks"
DEST="$ROOT/.git/hooks"

mkdir -p "$DEST"

for hook in pre-commit; do
  [ -f "$SRC/$hook" ] || continue

  # `sh "$HOOK"` rather than `exec "$HOOK"`: git on Windows does not reliably
  # preserve the executable bit, so invoking the interpreter explicitly is the
  # portable form. Losing +x would otherwise silently disable the hook — the
  # same class of quiet failure this shim exists to prevent.
  cat > "$DEST/$hook" <<SHIM
#!/bin/sh
# GENERATED by scripts/git-hooks/install-hooks.sh — do not edit.
# The real hook is the tracked file below, so this shim can never go stale.
ROOT=\$(git rev-parse --show-toplevel) || exit 0
HOOK="\$ROOT/scripts/git-hooks/$hook"
if [ ! -f "\$HOOK" ]; then
  echo "$hook: \$HOOK is missing — hook cannot run." >&2
  echo "Re-run: bash scripts/git-hooks/install-hooks.sh" >&2
  exit 1
fi
sh "\$HOOK" "\$@"
SHIM

  chmod +x "$DEST/$hook"
  echo "installed: .git/hooks/$hook -> scripts/git-hooks/$hook (shim)"
done

# ---------------------------------------------------------------------------
# Is .git/hooks even what git consults?
#
# 🔴 Added 2026-08-24, after finding that NO git hook had been running here.
# `core.hooksPath` overrides .git/hooks COMPLETELY. mobile/package.json runs
# `husky mobile/.husky` from the repo root in its "prepare" script, so any
# `npm install` under mobile/ sets core.hooksPath=mobile/.husky/_ for the whole
# repository. mobile/.husky/pre-commit was `exit 0`, so both gates below were
# silently dead - including the credential scan, on a PUBLIC repo - while this
# script cheerfully printed "Done. Both pre-commit gates are now live."
#
# Reporting "installed" when the installed thing cannot run is the same class of
# quiet failure the shim above exists to prevent, so verify instead of assuming.
# ---------------------------------------------------------------------------
HOOKS_PATH="$(git config --get core.hooksPath || true)"

if [ -n "$HOOKS_PATH" ]; then
  case "$HOOKS_PATH" in
    /*) HP="$HOOKS_PATH" ;;
     *) HP="$ROOT/$HOOKS_PATH" ;;
  esac

  # husky puts a dispatcher in <dir>/_ that sources <dir>/<hookname>, so check
  # both the directory git points at and its parent.
  DELEGATES=""
  for candidate in "$HP/pre-commit" "$(dirname "$HP")/pre-commit"; do
    if [ -f "$candidate" ] && grep -q "scripts/git-hooks/pre-commit" "$candidate" 2>/dev/null; then
      DELEGATES="$candidate"
      break
    fi
  done

  if [ -z "$DELEGATES" ]; then
    echo "" >&2
    echo "==============================================================" >&2
    echo " core.hooksPath = $HOOKS_PATH" >&2
    echo "" >&2
    echo " git IGNORES .git/hooks while that is set, so the shim this" >&2
    echo " script just wrote will NEVER RUN. Nothing above is live." >&2
    echo "" >&2
    echo " Point that hook at the repo gate, e.g. in" >&2
    echo "   $(dirname "$HP")/pre-commit" >&2
    echo " end with:  sh \"\$(git rev-parse --show-toplevel)/scripts/git-hooks/pre-commit\" \"\$@\"" >&2
    echo "" >&2
    echo " Or clear the override:  git config --unset core.hooksPath" >&2
    echo " (temporary - the next npm install under mobile/ re-sets it)" >&2
    echo "==============================================================" >&2
    exit 1
  fi

  echo ""
  echo "note: core.hooksPath = $HOOKS_PATH (git ignores .git/hooks)."
  echo "      $DELEGATES delegates to the repo gate, so it still runs."
fi

echo ""
echo "Done. Both pre-commit gates are now live:"
echo "  GATE A  credential scan          — every commit (needs git + grep)"
echo "  GATE B  staged PHP test verify   — when tests/*Test.php is staged"
echo "          (runs phpunit inside the nexus-php-app container; BLOCKS if"
echo "           the container is unavailable, rather than skipping quietly)"
