# Copyright © 2024–2026 Jasper Ford
# SPDX-License-Identifier: AGPL-3.0-or-later
# Author: Jasper Ford
# See NOTICE file for attribution and acknowledgements.
#
# R8 keep rules for the Play release build.
#
# WHY THIS FILE EXISTS SEPARATELY. `android/` is gitignored and regenerated by
# `expo prebuild` on every release build, so `android/app/proguard-rules.pro`
# cannot hold anything we need to keep. plugins/with-android-proguard-rules.js
# appends this file into the generated one, the same way
# with-android-network-security.js copies the network config in.
#
# 🔴 HOW TO THINK ABOUT THIS FILE. Minification does not break a React Native app
# at build time. Every rule below is here because something is looked up by a
# STRING at runtime — a class name, a field name, a method name — which R8
# cannot see and therefore renames or deletes. Nearly all of those call sites are
# wrapped in try/catch or runCatching upstream, so the failure is SILENT: a
# feature stops working and nothing is logged at the level anyone reads. Never
# delete a rule here because the build was clean.
#
# Rules are only listed when the dependency does NOT already ship them as
# consumer rules. Verified on 2026-09-12 against the installed versions by
# reading each package's android/build.gradle for `consumerProguardFiles` and
# each Maven AAR for an embedded `proguard.txt`. Already covered, so deliberately
# absent from this file:
#
#   react-native 0.83.10        AAR proguard.txt  (@DoNotStrip, NativeModule,
#                                                  native <methods>, ReactProp,
#                                                  bridge.**, turbomodule.**)
#   expo 55 (the package)       consumer rules    (ReactActivityDelegate public
#                                                  + protected, mDelegate,
#                                                  ExpoModulesPackageList members,
#                                                  WindowUtilKt)
#   expo-modules-core           consumer rules    (Module subclasses, Record,
#                                                  Enumerable enums, ExpoView)
#   react-native-reanimated     consumer rules
#   react-native-worklets       consumer rules
#   react-native-svg            consumer rules    (blanket com.horcrux.svg.**,
#                                                  which is what makes its
#                                                  getField(propName) safe)
#   expo-updates                consumer rules
#   expo-image                  consumer rules    (Glide + ThumbnailRequestCoordinator)
#   expo-location               consumer rules
#   @stripe/stripe-react-native consumer rules    (push provisioning, tapandpay)
#   stripe-android AARs         AAR proguard.txt
#   @sentry/react-native        sentry-android-core AAR proguard.txt, which also
#                               supplies -keepattributes LineNumberTable,SourceFile
#   kotlinx-serialization       META-INF/proguard inside the runtime jar
#   expo-secure-store,          no string-based lookups found; they are ordinary
#   @react-native-community/    Expo/React modules covered by the rules above
#   netinfo, expo-audio,
#   expo-video, expo-camera
#   (except the probe below)

# --------------------------------------------------------------------------
# Expo module registration. Fatal if lost — no Expo module would load at all.
#
# expo/android/.../ExpoModulesPackage.kt:23 and expo-modules-core's
# TaskServiceProviderHelper.kt:23 both do
#   Class.forName("expo.modules.ExpoModulesPackageList")
# The `expo` package's own consumer rule is `-keepclassmembers`, which keeps the
# MEMBERS but lets R8 rename the CLASS — and it is the class NAME that is looked
# up here. Keep the name too.
# --------------------------------------------------------------------------
-keep class expo.modules.ExpoModulesPackageList { *; }
-keep class inline.modules.ExpoInlineModulesList { *; }

# --------------------------------------------------------------------------
# Expo's ReactActivityDelegateWrapper. Fatal if lost — the app would not launch.
#
# expo/android/.../ReactActivityDelegateWrapper.kt calls
#   ReactActivityDelegate::class.java.getDeclaredMethod(name)
# for "getLaunchOptions", "createRootView", "getReactDelegate", "getContext",
# "getPlainActivity", "isFabricEnabled", "isWideColorGamutEnabled" and
# "composeLaunchOptions", and reads the fields `mDelegate` and `mReactDelegate`.
# Unlike most reflection in this list those calls are NOT wrapped in try/catch:
# a renamed member throws NoSuchMethodException on the launch path.
#
# The `expo` package ships `public *; protected *;` for this class. That is
# correct today, but it is one upstream visibility change away from a launch
# crash that no build check can see, so keep every member.
# --------------------------------------------------------------------------
-keepclassmembers class com.facebook.react.ReactActivityDelegate { *; }
-keepclassmembers class com.facebook.react.ReactActivity { *; }

# --------------------------------------------------------------------------
# Generated React Native module-info providers, looked up by string name.
#
# react-native-gesture-handler's RNGestureHandlerPackage.kt:57 does
#   Class.forName("com.swmansion.gesturehandler.RNGestureHandlerPackage$$ReactModuleInfoProvider")
# and falls back to reading a @ReactModule annotation with `!!` when that throws,
# so a rename turns into a NullPointerException rather than a graceful fallback.
# --------------------------------------------------------------------------
-keep class **$$ReactModuleInfoProvider { *; }

# --------------------------------------------------------------------------
# react-native-gesture-handler ships NO consumer rules at all, and
# react-native-reanimated's NativeProxy.java:80 reaches into it by name:
#   Class.forName("com.swmansion.gesturehandler.react.RNGestureHandlerModule")
# Without this, gesture/animation integration degrades silently. Matches the
# shape of reanimated's and worklets' own consumer rules.
# --------------------------------------------------------------------------
-keep class com.swmansion.gesturehandler.** { *; }

# --------------------------------------------------------------------------
# expo-notifications. Push notifications, so: sign-in prompts, messages, events.
#
# 🔴 The package DOES ship android/proguard-rules.pro with exactly this line —
# and its android/build.gradle has no `consumerProguardFiles` entry, so the file
# is never applied. Verified 2026-09-12 on expo-notifications 55.0.27. This is
# the reason the task brief says to verify rather than assume.
# --------------------------------------------------------------------------
-keep class expo.modules.notifications.** { *; }

# --------------------------------------------------------------------------
# expo-camera's MLKit availability probe — marketplace QR codes and event
# check-in scanning.
#   CameraUtils.kt:24  Class.forName("com.google.mlkit.vision.barcode.BarcodeScanning")
# Wrapped in `catch (_: ClassNotFoundException) { false }`, so a rename does not
# crash: the scanner just reports itself unavailable.
# --------------------------------------------------------------------------
-keep class com.google.mlkit.vision.barcode.BarcodeScanning { *; }

# --------------------------------------------------------------------------
# expo-image-picker's crop screen — every avatar, post, listing and logo upload.
#   ExpoCropImageActivity.kt:154  getDeclaredField("cropImageOptions")
#   ExpoCropImageActivity.kt:161  getDeclaredMethod("setCustomizations")
# on com.canhub.cropper.CropImageActivity (com.vanniktech:android-image-cropper),
# which ships no rules. Both are inside runCatching{}.getOrNull(), so the crop
# UI silently loses its theming rather than failing loudly.
# The class itself is referenced as a class literal, so R8 tracks the rename —
# only the member names need pinning.
# --------------------------------------------------------------------------
-keepclassmembers class com.canhub.cropper.CropImageActivity {
  *** cropImageOptions;
  *** setCustomizations();
}

# --------------------------------------------------------------------------
# Stripe card entry. Cosmetic, but on the payment screen.
#   CardFieldView.kt:198 getDeclaredMethod("setTintColorInt$payments_core_release")
# on com.stripe.android.view.CardBrandView (payments-core). Caught and logged,
# so the card-brand icon simply keeps the wrong tint.
# --------------------------------------------------------------------------
-keepclassmembers class com.stripe.android.view.CardBrandView {
  *** setTintColorInt$payments_core_release(int);
}

# --------------------------------------------------------------------------
# Stripe Issuing push provisioning — an OPTIONAL Stripe artifact this app does
# not depend on and does not use.
#
# This is the one rule here that R8 demands at BUILD time rather than one that
# prevents a silent runtime failure. @stripe/stripe-react-native's
# DefaultPushProvisioningProxy references com.stripe.android.pushProvisioning.*,
# which lives in com.stripe:stripe-android-issuing-push-provisioning. That
# artifact is opt-in and is not in this app's dependency graph, so R8 refuses
# with "Missing classes detected". Building version code 11 on 2026-09-12 it
# named exactly five: PushProvisioningActivity$g,
# PushProvisioningActivityStarter{,$Args,$Error} and
# PushProvisioningEphemeralKeyProvider.
#
# Suppressing the whole package rather than those five: the entire package is in
# the absent artifact, and Stripe's own guidance is to silence it when Issuing is
# not used. Nothing in mobile/ calls canAddCardToWallet, isCardInWallet or any
# push-provisioning API — checked before writing this. If this app ever adds
# Stripe Issuing, add the dependency and DELETE this rule.
# --------------------------------------------------------------------------
-dontwarn com.stripe.android.pushProvisioning.**

# --------------------------------------------------------------------------
# Keep the source file and line numbers in Java/Kotlin stack traces.
#
# sentry-android-core's AAR already asks for this, but it is the difference
# between a readable and an unreadable native crash in Play Console, and it must
# not depend on a transitive dependency's rules. `-renamesourcefileattribute` is
# deliberately NOT set: Play deobfuscates using the mapping file inside the AAB,
# and Sentry has no Android Gradle plugin configured here to upload one.
# --------------------------------------------------------------------------
-keepattributes SourceFile,LineNumberTable
