#!/usr/bin/env bash
# Copyright © 2024–2026 Jasper Ford
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# build-aab-play.sh — build the SIGNED Android App Bundle that goes to Google Play,
# on this machine, with no EAS quota spent.
#
# 🔴 Why this exists. There was no checked-in recipe for the artefact we actually
# ship. `build-apk-local.sh` builds a DEBUG-SIGNED APK for sideloading and says so;
# the Play bundle was being produced by hand. Three things about that go wrong
# silently, and all three produce a file that looks completely normal:
#
#   1. SIGNING. android/app/build.gradle:133 reads
#        release { signingConfig playStoreFile ? playRelease : signingConfigs.debug }
#      With the signing values absent, Gradle does not fail — it signs with the
#      DEBUG key and still writes app-release.aab. Play rejects it, and if it did
#      not, it could never update the installed app.
#
#   2. THE API HOST. Expo bakes EXPO_PUBLIC_API_URL into the bundle at build time
#      from .env.production.local. On 2026-09-09 that file — regenerated by
#      build-apk-local.sh during emulator testing — still read
#      http://10.0.2.2:8090, the EMULATOR's name for the build machine. A release
#      built from it points at somebody's laptop, works perfectly on an emulator,
#      and is dead in every real user's hand.
#
#   3. ARCHITECTURES. `expo run:android` writes reactNativeArchitectures=<one abi>
#      into android/gradle.properties. A later release build inherits it and ships
#      native code for one CPU. On 2026-08-20 that produced an x86_64-only build:
#      flawless on the emulator, "App not installed" on a real phone.
#
#   4. OVER-THE-AIR UPDATES. Found on 2026-09-10 by opening the bundle that had
#      gone to Play as version code 8: it carried NO update channel and a runtime
#      version of 1.2.0 inside an app labelled 1.4.0. EAS-built binaries get the
#      channel written in by the build service; a local Gradle build gets it only
#      from `updates.requestHeaders` in app.json, which nothing set. And this
#      script only ran `expo prebuild` when android/ was missing, so the generated
#      strings.xml kept whatever runtime version it had when the folder was first
#      created — an August value. Either fault alone means the Expo update
#      service serves that build nothing, ever: no fix can reach it without a new
#      store release. The native project is now regenerated on every build, and
#      the finished bundle is opened and checked for both values.
#
# Every one of those is checked below and refuses the build rather than warning.
#
# Usage:
#   bash scripts/build-aab-play.sh --version-code 8
#   bash scripts/build-aab-play.sh --version-code 8 --clean
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

VERSION_CODE=""
CLEAN=0
while [ $# -gt 0 ]; do
  case "$1" in
    --version-code) VERSION_CODE="${2:-}"; shift 2;;
    --clean) CLEAN=1; shift;;
    *) echo "unknown argument: $1" >&2; exit 2;;
  esac
done

if ! printf '%s' "$VERSION_CODE" | grep -qE '^[0-9]+$'; then
  echo "ERROR: --version-code is required and must be a number." >&2
  echo "It must be HIGHER than the version code already live on Play, or Play" >&2
  echo "refuses the upload. Check: Play Console -> Production -> latest release." >&2
  exit 2
fi

API_URL="${API_URL:-https://api.project-nexus.ie}"
APP_URL="${APP_URL:-https://app.project-nexus.ie}"
TENANT="${TENANT:-hour-timebank}"

# ---------------------------------------------------------------- guard 1: host
# A release must never be pointed at a loopback, a private LAN address or the
# emulator's 10.0.2.2 alias. lib/constants.ts refuses a loopback at runtime when
# __DEV__ is false, but by then the build exists and may already be uploaded.
case "$API_URL" in
  *localhost*|*127.0.0.1*|*10.0.2.2*|*192.168.*|*http://*)
    echo "ERROR: refusing to build a release against '$API_URL'." >&2
    echo "A Play build must target the public HTTPS API. Set API_URL explicitly if" >&2
    echo "you really mean something else." >&2
    exit 1;;
esac

# ------------------------------------------------------- guard 2: signing keys
if [ ! -f credentials.json ]; then
  echo "ERROR: mobile/credentials.json not found — that is where the upload key" >&2
  echo "and its passwords live. Without it Gradle would DEBUG-sign the bundle." >&2
  exit 1
fi

read_cred() {
  node -e "const c=require('./credentials.json');const v=c.android.keystore['$1'];if(!v){process.exit(3)}process.stdout.write(String(v))"
}

KEYSTORE_REL="$(read_cred keystorePath)"
KEY_ALIAS="$(read_cred keyAlias)"
KEYSTORE_ABS="$ROOT/$KEYSTORE_REL"

if [ ! -f "$KEYSTORE_ABS" ]; then
  echo "ERROR: keystore missing at $KEYSTORE_ABS" >&2
  exit 1
fi

# Passwords are read into the environment and never echoed. Gradle picks them up
# via System.getenv in android/app/build.gradle.
PLAY_STORE_PASSWORD="$(read_cred keystorePassword)"; export PLAY_STORE_PASSWORD
PLAY_KEY_PASSWORD="$(read_cred keyPassword)";       export PLAY_KEY_PASSWORD
PLAY_STORE_FILE="$KEYSTORE_ABS";                    export PLAY_STORE_FILE
PLAY_KEY_ALIAS="$KEY_ALIAS";                        export PLAY_KEY_ALIAS

# ------------------------------------------------------------ native project
# 🔴 Always. Prebuild is what copies app.json into AndroidManifest.xml and
# strings.xml — the update channel, the runtime version, permissions. Running it
# only when android/ was missing is how version code 8 shipped with a runtime
# version from August (see header, item 4).
echo "Regenerating the native project from app.json …"
npx expo prebuild --platform android --no-install

# Certificate pins live in the source file; the config plugin copies them in on
# prebuild, so copy them here too in case no prebuild has run since they changed.
mkdir -p android/app/src/main/res/xml
cp android-network-security-config.xml android/app/src/main/res/xml/network_security_config.xml

# ------------------------------------------------------------------- bundle env
SENTRY_DSN=""
if [ -f "../.secrets.local/sentry.env" ]; then
  SENTRY_DSN="$(grep '^SENTRY_DSN_MOBILE=' "../.secrets.local/sentry.env" | cut -d= -f2- || true)"
fi

cat > .env.production.local <<EOF
# Generated by scripts/build-aab-play.sh — safe to delete.
EXPO_PUBLIC_API_URL=${API_URL}
EXPO_PUBLIC_APP_URL=${APP_URL}
EXPO_PUBLIC_DEFAULT_TENANT=${TENANT}
EXPO_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
EXPO_PUBLIC_E2E=0
EOF

echo "API for this build : ${API_URL}"
echo "Version code       : ${VERSION_CODE}"
echo "Signing alias      : ${KEY_ALIAS}"
[ -n "$SENTRY_DSN" ] && echo "Crash reporting    : ON" || echo "Crash reporting    : OFF (no SENTRY_DSN_MOBILE)"
echo ""

# ----------------------------------------------------------------------- build
cd android
[ "$CLEAN" = "1" ] && ./gradlew clean --no-daemon

# 🔴 All four architectures passed explicitly — see the header. Never rely on
# whatever gradle.properties happens to say.
SENTRY_DISABLE_AUTO_UPLOAD=true ./gradlew bundleRelease \
  -PplayVersionCode="${VERSION_CODE}" \
  -PreactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64 \
  --no-daemon

cd ..
AAB="android/app/build/outputs/bundle/release/app-release.aab"

if [ ! -f "$AAB" ]; then
  echo "BUILD REPORTED SUCCESS BUT THERE IS NO BUNDLE AT ${AAB}" >&2
  echo "Do not treat this as a pass." >&2
  exit 1
fi

# ------------------------------------------------- guard 3: prove it is signed
# A debug-signed bundle is the failure this script exists to prevent, so verify
# rather than assume. The upload certificate is the one Play knows us by.
EXPECTED="F5:0D:87:55:56:B8:01:76:3D:89:B2:54:47:E7:CD:96:58:06:FE:43:96:1C:0B:46:12:2D:42:4E:0B:40:D9:7B"
KEYTOOL="${JAVA_HOME:+$JAVA_HOME/bin/keytool}"
[ -x "$KEYTOOL" ] || KEYTOOL="$(command -v keytool || true)"

if [ -n "$KEYTOOL" ]; then
  ACTUAL="$("$KEYTOOL" -printcert -jarfile "$AAB" 2>/dev/null | grep -i 'SHA256:' | head -1 | sed 's/.*SHA256:[[:space:]]*//' | tr -d '[:space:]')"
  if [ "$ACTUAL" = "$(printf '%s' "$EXPECTED" | tr -d '[:space:]')" ]; then
    echo "Signature verified: Play upload key."
  else
    echo "ERROR: bundle is NOT signed with the Play upload key." >&2
    echo "  expected $EXPECTED" >&2
    echo "  actual   ${ACTUAL:-<unsigned or unreadable>}" >&2
    echo "Do not upload this file." >&2
    exit 1
  fi
else
  echo "WARNING: keytool not found — signature NOT verified. This is not a pass." >&2
fi

# ------------------------------- guard 4: prove the bundle can receive updates
# Both values are read from the FINISHED bundle, not from the sources that should
# have produced them. The manifest and resources inside an .aab are protobuf, but
# the strings are stored verbatim, so a byte search is a reliable check.
APP_VERSION="$(node -e "process.stdout.write(require('./app.json').expo.version)")"
EXPECTED_CHANNEL="$(node -e "process.stdout.write(require('./app.json').expo.updates.requestHeaders['expo-channel-name'])")"
if [ -z "$EXPECTED_CHANNEL" ]; then
  echo "ERROR: app.json has no updates.requestHeaders['expo-channel-name']; a local build" >&2
  echo "would listen to no update channel and could never receive a fix." >&2
  exit 1
fi
if ! unzip -p "$AAB" base/manifest/AndroidManifest.xml | grep -a -q "expo-channel-name"; then
  echo "ERROR: the bundle's manifest carries no update channel header." >&2
  echo "Members on this build could never receive an over-the-air update." >&2
  exit 1
fi
if ! unzip -p "$AAB" base/manifest/AndroidManifest.xml | grep -a -q "\"expo-channel-name\":\"${EXPECTED_CHANNEL}\""; then
  echo "ERROR: the bundle's update channel is not '${EXPECTED_CHANNEL}'." >&2
  exit 1
fi
if ! unzip -p "$AAB" base/resources.pb | grep -a -q "${APP_VERSION}"; then
  echo "ERROR: the bundle's runtime version is not ${APP_VERSION} (app.json version)." >&2
  echo "Updates published for ${APP_VERSION} would be refused by this build." >&2
  exit 1
fi
echo "Update channel     : ${EXPECTED_CHANNEL} (verified in bundle)"
echo "Runtime version    : ${APP_VERSION} (verified in bundle)"

echo ""
echo "Bundle: $ROOT/$AAB"
du -h "$AAB" | cut -f1
