#!/usr/bin/env bash
# Copyright © 2024–2026 Jasper Ford
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# build-apk-local.sh — build an installable Android APK on THIS machine, no EAS, no cost.
#
# 🔴 Why this exists: EAS cloud builds are billed per build, and for "put it on my phone
# and try it" there is nothing a paid build does that Gradle here does not. The paid
# service earns its money for store submissions and for builds from a clean machine — not
# for iteration.
#
# What you get: android/app/build/outputs/apk/release/app-release.apk — a standalone APK
# with the JavaScript bundled in, so it runs with no Metro and no laptop attached.
#
# 🔴 SIGNING. The Expo/React Native template signs `release` with the DEBUG keystore
# (android/app/build.gradle: `release { signingConfig signingConfigs.debug }`). That is
# fine for sideloading onto your own phone and is why this needs no setup. It is NOT fine
# for the Play Store, and a device will refuse to install a differently-signed build over
# it later — uninstall first. Generating a real upload keystore is a separate decision,
# because losing that file means never being able to update the app again.
#
# Usage:
#   bash scripts/build-apk-local.sh              # points at the live API
#   bash scripts/build-apk-local.sh --clean      # wipe build caches first (slower, surer)
#   API_URL=http://192.168.1.36:8090 bash scripts/build-apk-local.sh
#                                                # point at THIS machine's LAN address
set -euo pipefail

cd "$(dirname "$0")/.."

CLEAN=0
for arg in "$@"; do
  [ "$arg" = "--clean" ] && CLEAN=1
done

API_URL="${API_URL:-https://api.project-nexus.ie}"
APP_URL="${APP_URL:-https://app.project-nexus.ie}"
TENANT="${TENANT:-hour-timebank}"

if [ ! -d android ]; then
  echo "No android/ project yet — generating it (this is normal on a fresh clone)."
  npx expo prebuild --platform android
fi

# 🔴 The native project is regenerated by prebuild and is gitignored, so the certificate
# pins live in the SOURCE file and are copied in by the config plugin. If a prebuild has
# not run since the pins changed, the APK would ship the old ones. Copy is what the plugin
# does, so doing it here is equivalent and cheap.
mkdir -p android/app/src/main/res/xml
cp android-network-security-config.xml android/app/src/main/res/xml/network_security_config.xml

# 🔴 Expo loads .env.production.local ABOVE .env.local, which matters because .env.local
# normally holds http://10.0.2.2:8090 — the EMULATOR's name for this machine, meaningless
# on a real phone. Writing it here rather than editing .env.local leaves your dev setup
# alone. (lib/constants.ts also refuses a loopback URL when __DEV__ is false, after that
# exact value was once baked into a real build.)
# 🔴 Crash reporting, from the machine-local secrets file rather than a literal here — the
# repository is public. Without a DSN, `Sentry.init` runs with `enabled: false` and a build
# handed to a real person reports nothing at all when it breaks. Optional on purpose: a
# machine without the secrets file still builds, it just says so.
SENTRY_DSN=""
SENTRY_ENV_FILE="../.secrets.local/sentry.env"
if [ -f "$SENTRY_ENV_FILE" ]; then
  SENTRY_DSN="$(grep '^SENTRY_DSN_MOBILE=' "$SENTRY_ENV_FILE" | cut -d= -f2- || true)"
fi

cat > .env.production.local <<EOF
# Generated by scripts/build-apk-local.sh — safe to delete.
EXPO_PUBLIC_API_URL=${API_URL}
EXPO_PUBLIC_APP_URL=${APP_URL}
EXPO_PUBLIC_DEFAULT_TENANT=${TENANT}
EXPO_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
# Never inherit the debug-only Maestro/LogBox setting from .env.local into a
# production-bundled APK used for release screenshots.
EXPO_PUBLIC_E2E=0
EOF

if [ -n "$SENTRY_DSN" ]; then
  echo "Crash reporting: ON (nexus-mobile)"
else
  echo "Crash reporting: OFF — no SENTRY_DSN_MOBILE in .secrets.local/sentry.env"
fi

echo "API for this build: ${API_URL}"
echo ""

cd android
if [ "$CLEAN" = "1" ]; then
  echo "Cleaning…"
  ./gradlew clean --no-daemon
fi

# SENTRY_DISABLE_AUTO_UPLOAD: without it the Sentry Gradle plugin tries to upload source
# maps and can fail the build when no Sentry org/token is configured — which is the case
# here, since crash reporting goes to our own API instead.
# 🔴 ALL FOUR architectures, passed explicitly, and this line is the whole reason this
# script exists rather than a bare gradlew call.
#
# `npx expo run:android` WRITES `reactNativeArchitectures=<connected device abi>` into
# android/gradle.properties to make local dev builds fast. Any later `assembleRelease`
# inherits it silently. On 2026-08-20 that produced a 50MB APK containing ONLY x86_64
# native libraries. It installed perfectly on the emulator — which IS x86_64 — and a real
# arm64 phone refused it outright with a bare "App not installed", because there was no
# code in it the phone could run.
#
# The APK was otherwise perfect: correct bundle, correct API host, correct certificate
# pins, right package, right signature, higher version. Every check passed except the one
# that mattered, and testing on the emulator could never have caught it.
SENTRY_DISABLE_AUTO_UPLOAD=true ./gradlew assembleRelease   -PreactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64 --no-daemon

cd ..
APK="android/app/build/outputs/apk/release/app-release.apk"

if [ ! -f "$APK" ]; then
  echo "BUILD REPORTED SUCCESS BUT THERE IS NO APK AT ${APK}" >&2
  echo "Do not treat this as a pass — check the Gradle output above." >&2
  exit 1
fi

SIZE=$(du -h "$APK" | cut -f1)

# 🔴 Verify the ARCHITECTURES in the artefact, not the flag we passed. A phone with no
# matching native library refuses the install with no useful message, and the emulator
# cannot reveal it.
python - "$APK" <<'PY'
import sys, zipfile
from collections import Counter
z = zipfile.ZipFile(sys.argv[1])
abis = Counter(n.split('/')[1] for n in z.namelist() if n.startswith('lib/'))
required = {'arm64-v8a', 'armeabi-v7a'}
missing = required - set(abis)
print(f"architectures in the APK: {dict(abis)}")
if missing:
    print(f"REFUSING: no {', '.join(sorted(missing))} — a real phone cannot install this.")
    sys.exit(1)
print("arm64-v8a present, so a modern phone can install it.")
PY

echo ""
echo "APK built: ${APK}  (${SIZE})"
echo ""
echo "Put it on a phone, whichever suits:"
echo "  1. USB:  adb install -r \"${APK}\""
echo "  2. File: copy the APK to the phone and tap it (allow 'install unknown apps')"
echo ""
echo "It talks to ${API_URL}. Sign in with a real account."
