#!/usr/bin/env bash
# Copyright © 2024–2026 Jasper Ford
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# build-apk-local.sh — build an installable Android APK on THIS machine, no EAS, no cost.
#
# 🔴 Why this exists: EAS cloud builds are billed per build, and for "put it on my phone
# and try it" there is nothing a paid build does that Gradle here does not. The paid
# service earns its money for store submissions and for builds from a clean machine — not
# for iteration.
#
# What you get: android/app/build/outputs/apk/release/app-release.apk — a standalone APK
# with the JavaScript bundled in, so it runs with no Metro and no laptop attached.
#
# 🔴 SIGNING. The Expo/React Native template signs `release` with the DEBUG keystore
# (android/app/build.gradle: `release { signingConfig signingConfigs.debug }`). That is
# fine for sideloading onto your own phone and is why this needs no setup. It is NOT fine
# for the Play Store, and a device will refuse to install a differently-signed build over
# it later — uninstall first. Generating a real upload keystore is a separate decision,
# because losing that file means never being able to update the app again.
#
# Usage:
#   bash scripts/build-apk-local.sh              # points at the live API
#   bash scripts/build-apk-local.sh --clean      # wipe build caches first (slower, surer)
#   API_URL=http://192.168.1.36:8090 bash scripts/build-apk-local.sh
#                                                # point at THIS machine's LAN address
set -euo pipefail

cd "$(dirname "$0")/.."

CLEAN=0
for arg in "$@"; do
  [ "$arg" = "--clean" ] && CLEAN=1
done

API_URL="${API_URL:-https://api.project-nexus.ie}"
APP_URL="${APP_URL:-https://app.project-nexus.ie}"
TENANT="${TENANT:-hour-timebank}"

if [ ! -d android ]; then
  echo "No android/ project yet — generating it (this is normal on a fresh clone)."
  npx expo prebuild --platform android
fi

# 🔴 The native project is regenerated by prebuild and is gitignored, so the certificate
# pins live in the SOURCE file and are copied in by the config plugin. If a prebuild has
# not run since the pins changed, the APK would ship the old ones. Copy is what the plugin
# does, so doing it here is equivalent and cheap.
mkdir -p android/app/src/main/res/xml
cp android-network-security-config.xml android/app/src/main/res/xml/network_security_config.xml

# 🔴 Expo loads .env.production.local ABOVE .env.local, which matters because .env.local
# normally holds http://10.0.2.2:8090 — the EMULATOR's name for this machine, meaningless
# on a real phone. Writing it here rather than editing .env.local leaves your dev setup
# alone. (lib/constants.ts also refuses a loopback URL when __DEV__ is false, after that
# exact value was once baked into a real build.)
cat > .env.production.local <<EOF
# Generated by scripts/build-apk-local.sh — safe to delete.
EXPO_PUBLIC_API_URL=${API_URL}
EXPO_PUBLIC_APP_URL=${APP_URL}
EXPO_PUBLIC_DEFAULT_TENANT=${TENANT}
EOF

echo "API for this build: ${API_URL}"
echo ""

cd android
if [ "$CLEAN" = "1" ]; then
  echo "Cleaning…"
  ./gradlew clean --no-daemon
fi

# SENTRY_DISABLE_AUTO_UPLOAD: without it the Sentry Gradle plugin tries to upload source
# maps and can fail the build when no Sentry org/token is configured — which is the case
# here, since crash reporting goes to our own API instead.
SENTRY_DISABLE_AUTO_UPLOAD=true ./gradlew assembleRelease --no-daemon

cd ..
APK="android/app/build/outputs/apk/release/app-release.apk"

if [ ! -f "$APK" ]; then
  echo "BUILD REPORTED SUCCESS BUT THERE IS NO APK AT ${APK}" >&2
  echo "Do not treat this as a pass — check the Gradle output above." >&2
  exit 1
fi

SIZE=$(du -h "$APK" | cut -f1)
echo ""
echo "APK built: ${APK}  (${SIZE})"
echo ""
echo "Put it on a phone, whichever suits:"
echo "  1. USB:  adb install -r \"${APK}\""
echo "  2. File: copy the APK to the phone and tap it (allow 'install unknown apps')"
echo ""
echo "It talks to ${API_URL}. Sign in with a real account."
