// Copyright (c) 2024-2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexus.Api.Migrations;

/// <summary>
/// Creates three tables the EF model has always believed existed.
///
/// 🔴 The same failure class as the migration-163 repair
/// (compatibility_audit_entries): the entity is mapped, the model snapshot
/// carries it, `has-pending-model-changes` reports clean, every build and test
/// passes — and no migration ever emitted the CreateTable, so the table is
/// simply absent from the database. Any query against it throws
/// `42P01 relation does not exist` at runtime.
///
/// It stayed hidden because the endpoints that would have touched these tables
/// were no-op stubs (R-1): nothing ever queried them, so nothing ever failed.
/// Found on 2026-08-15 by implementing GET /v2/volunteering/training for real
/// and watching it throw.
///
/// Detector: `.local-docs-archive/find_phantom_tables.py` compares every
/// `ToTable(...)` in the snapshot against every `CreateTable` across the
/// migration chain. It found exactly these three out of 439 mapped tables.
/// Worth re-running after any migration surgery.
///
/// <c>IF NOT EXISTS</c> is used throughout because a database that was created
/// by <c>EnsureCreated</c> (which builds from the model, not the chain) may
/// already have them.
/// </summary>
public partial class CreateMissingVolunteerAdminTables : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS volunteer_training_courses (
                "Id"              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TenantId"        integer NOT NULL,
                "Title"           text NOT NULL,
                "Description"     text NULL,
                "DurationMinutes" integer NOT NULL DEFAULT 0,
                "IsRequired"      boolean NOT NULL DEFAULT FALSE,
                "Active"          boolean NOT NULL DEFAULT TRUE,
                "CreatedAt"       timestamp with time zone NOT NULL DEFAULT NOW(),
                "UpdatedAt"       timestamp with time zone NULL,
                CONSTRAINT "FK_volunteer_training_courses_tenants_TenantId"
                    FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE RESTRICT
            );
            CREATE INDEX IF NOT EXISTS "IX_volunteer_training_courses_TenantId"
                ON volunteer_training_courses ("TenantId");
            CREATE INDEX IF NOT EXISTS "IX_volunteer_training_courses_Active"
                ON volunteer_training_courses ("Active");

            CREATE TABLE IF NOT EXISTS volunteer_training_completions (
                "Id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TenantId"       integer NOT NULL,
                "UserId"         integer NOT NULL,
                "CourseId"       integer NOT NULL,
                "CompletedAt"    timestamp with time zone NOT NULL DEFAULT NOW(),
                "Score"          integer NULL,
                "CertificateUrl" text NULL,
                CONSTRAINT "FK_volunteer_training_completions_tenants_TenantId"
                    FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_volunteer_training_completions_users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_volunteer_training_completions_courses_CourseId"
                    FOREIGN KEY ("CourseId") REFERENCES volunteer_training_courses ("Id") ON DELETE CASCADE
            );
            CREATE INDEX IF NOT EXISTS "IX_volunteer_training_completions_TenantId"
                ON volunteer_training_completions ("TenantId");
            -- One completion per volunteer per course, matching the model.
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_volunteer_training_completions_UserId_CourseId"
                ON volunteer_training_completions ("UserId", "CourseId");

            CREATE TABLE IF NOT EXISTS volunteer_tenant_policies (
                "Id"                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TenantId"                    integer NOT NULL,
                "MinAge"                      integer NOT NULL DEFAULT 0,
                "RequireGuardianConsentUnder" integer NOT NULL DEFAULT 0,
                "AutoApproveVerifiedAdults"   boolean NOT NULL DEFAULT FALSE,
                "HoursRequiredForCertificate" numeric NOT NULL DEFAULT 0,
                "CertificateTemplateId"       integer NULL,
                "UpdatedAt"                   timestamp with time zone NOT NULL DEFAULT NOW(),
                CONSTRAINT "FK_volunteer_tenant_policies_tenants_TenantId"
                    FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE RESTRICT
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_volunteer_tenant_policies_TenantId"
                ON volunteer_tenant_policies ("TenantId");
            """);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS volunteer_training_completions;
            DROP TABLE IF EXISTS volunteer_training_courses;
            DROP TABLE IF EXISTS volunteer_tenant_policies;
            """);
    }
}
