// Copyright © 2024–2026 Jasper Ford
// SPDX-License-Identifier: AGPL-3.0-or-later
// Author: Jasper Ford
// See NOTICE file for attribution and acknowledgements.

import { execFileSync } from 'child_process';
import { existsSync, readFileSync } from 'fs';

const EXCLUDED_FILENAMES = new Set([
  'expo-env.d.ts',
  // Generated by uniwind ("should not be edited manually" header) — a SPDX
  // header here would be wiped on the next codegen, reintroducing the failure.
  'uniwind-types.d.ts',
  // Generated by i18next-cli ("automatically generated ... Do not edit manually"
  // header) — a SPDX header here would be wiped on the next codegen, reintroducing
  // the failure.
  'resources.d.ts',
]);

const EXCLUDED_PATH_PARTS = new Set([
  'node_modules',
  'vendor',
  'dist',
  'build',
  '.git',
  '.expo',
]);

function isExcluded(path) {
  const normalized = path.replaceAll('\\', '/');
  const parts = normalized.split('/');
  const filename = parts.at(-1);

  return EXCLUDED_FILENAMES.has(filename) || parts.some((part) => EXCLUDED_PATH_PARTS.has(part));
}

// 🔴 web-uk is JavaScript and Nunjucks, so scanning only PHP/TS/TSX left the
// whole accessible frontend outside this gate — and it showed: 5 of its source
// files and 63 of its 335 templates had no licence header at all, despite
// AGENTS.md and web-uk/CLAUDE.md both requiring one (CLAUDE.md even spells out
// the `{# … #}` form for templates). Added 2026-08-12 after an audit found them.
//
// Deliberately scoped to `web-uk/src` rather than `*.js` repo-wide. A blanket
// JavaScript rule would sweep in build configs, generated output and tooling
// across react-frontend, e2e, mobile and scripts — hundreds of files that have
// never carried a header — turning one honest gap into a red gate nobody can
// clear. Widen this deliberately, per directory, not by accident.
const trackedFiles = execFileSync('git', [
  'ls-files',
  '*.php',
  '*.ts',
  '*.tsx',
  'web-uk/src/*.js',
  'web-uk/src/*.njk',
], {
  encoding: 'utf8',
})
  .split(/\r?\n/)
  .filter(Boolean)
  .filter((path) => !isExcluded(path));

const missing = [];

for (const file of trackedFiles) {
  if (!existsSync(file)) {
    continue;
  }
  const content = readFileSync(file, 'utf8');
  if (!content.includes('SPDX-License-Identifier')) {
    missing.push(file);
  }
}

const existingFiles = trackedFiles.filter((file) => existsSync(file));
const withHeader = existingFiles.length - missing.length;

console.log(`tracked source: ${existingFiles.length} files, ${withHeader} with header, ${missing.length} missing`);
if (missing.length > 0) {
  missing.forEach((file) => console.log(`  MISSING: ${file}`));
}

if (missing.length === 0) {
  console.log('ALL FILES HAVE SPDX HEADERS');
} else {
  console.error(`ERROR: ${missing.length} files are missing SPDX headers!`);
  process.exitCode = 1;
}
